// <auto-generated />
using System;
using EmbrujoCerveza.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmbrujoCerveza.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250924053313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.16");

            modelBuilder.Entity("EmbrujoCerveza.Web.Models.BeerLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeerStyleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BottleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BottleTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BottledOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BeerStyleId");

                    b.HasIndex("BottleTypeId");

                    b.ToTable("BeerLots");
                });

            modelBuilder.Entity("EmbrujoCerveza.Web.Models.BeerStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Abv")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Ibu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BeerStyles");
                });

            modelBuilder.Entity("EmbrujoCerveza.Web.Models.BottleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityMl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BottleTypes", (string)null);
                });

            modelBuilder.Entity("EmbrujoCerveza.Web.Models.BeerLot", b =>
                {
                    b.HasOne("EmbrujoCerveza.Web.Models.BeerStyle", "BeerStyle")
                        .WithMany("Lots")
                        .HasForeignKey("BeerStyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmbrujoCerveza.Web.Models.BottleType", "BottleType")
                        .WithMany("Lots")
                        .HasForeignKey("BottleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeerStyle");

                    b.Navigation("BottleType");
                });

            modelBuilder.Entity("EmbrujoCerveza.Web.Models.BeerStyle", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("EmbrujoCerveza.Web.Models.BottleType", b =>
                {
                    b.Navigation("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
